name: dart_bigquery
description: A web server built using the shelf package.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  shelf: ^1.2.0

dev_dependencies:
  pedantic: ^1.10.0
